### ISSUE TITLE
Another leak

### ISSUE THREAD

**Issue by the8472** [Quicksaver/Tab-Groups#196]
* open some site that gets redrawn frequently, e.g. a youtube video
* open `about:memory`
* measure
* take a look at `dom/memory-file-data/large` (might be under tiny)
* open / close tab view repeatedly
* measure again

Can you confirm that you see the stats growing? I've also tried this with 1c164fe9701e2f9b19a9678bf06290aa1d338842 so it doesn't seem to be related to createObjectURL.

**Comment by Quicksaver** [comment]
Unfortunately I can't debug this on my computer, as soon as I start a video, that's really all it can do, even about:memory is too much for it then. :(

Do you know what exactly memory-file-data usually refers to? Could it be holding on to blobs/images temporarily until they are discarded by CC/GC?

**Comment by the8472** [comment]
A site with some CSS animation or animated gif might work too for testing.

I have manually triggered GCs and it doesn't go away. And I don't know more than you here, images/blobs would be my guess too, but that's just a guess.

**Comment by Quicksaver** [comment]
Hmm, can you check if you see the same thing with http://www.w3schools.com/css/tryit.asp?filename=trycss3_animation_count2?

**Comment by the8472** [comment]
Yes, but in that case it only works if the page is the active tab, otherwise it doesn't seem to update the preview.

**Comment by Quicksaver** [comment]
Exactly but in that page I'm not sure I'm seeing that same as you. I have a few to several different entries under memory-file-data, but they always have different sha1 checksums every time I measure, so they are (or should be) different things; except for a usual and single object that keeps a constant sha1 (probably from some image or thumb that doesn't change, but that's expected.

Hypothesis: what you're seeing is the memory going up from your canvases being built one at a time (which should be stricter now since #185), and it doesn't go down because you don't spend enough time outside of tab view for them to be destroyed.

**Comment by the8472** [comment]
I'm seeing those numbers, both in MB and number of hashes, go up over time. Fairly slowly but it adds up.

I noticed this after leaving the tab view open over night, which accumulated 1GB of `dom/memory-file-data`

**Comment by Quicksaver** [comment]
Hmm, I wonder if it's keeping temp blobs lying around...

**Comment by the8472** [comment]
There are some obvious suspects around the area of blobs, canvases and the thumbnail service, but can you confirm it happening? If not then some other factors could be at play, e.g. e10s, hw acceleration, nightly...

**Comment by Quicksaver** [comment]
I was about to mention that, I just gave it another run and I don't see the number of hashes go up (and stay up). I'm trying in Win7x64 in Nightly with e10s and hw enabled though. Different from you?

**Comment by the8472** [comment]
it's similar. w10 x64, nightly, hw acceleration.

**Comment by Quicksaver** [comment]
Well, a good starting point could be to disable the tab thumbnails in the group of that actively updating tab, at least that would confirm or rule out the canvas work.

I'll still give it a few more tries with different tabs and combos to see if I can reproduce it on my end.

**Comment by Quicksaver** [comment]
Does 3c7f366d3f65d1992f32fcc9eb982ae058b75fcf make a difference?

**Comment by the8472** [comment]
Well, not what you asked, but I tested with df913d0f529b6a07cb6bd061be6a2e83ce695964

It seems that `tabview.xhtml` is now kept alive after disabling the addon.

The culprit here seems to be `Watchers.jsm` registrations not being cleaned up properly, this might be due to da47c8080f217189bdaffdbcf5be8bb5da31e5f8

```
000001860F0C7240 [JS Object (Window)]
    --[UnwrapDOMObject(obj)]--> 000001860C5A2800 [nsGlobalWindow # 41 inner chrome://tabgroups/content/tabview.xhtml]

    Root 000001860F0C7240 is a marked GC object.

via mCallback :
0000018612872730 [XULElement <no private>]
    --[_firstTab, _lastTab]--> 000001860DD1F850 [XULElement <no private>]
    --[_WATCHERS_tabGroups]--> 000001860DD07FE0 [Proxy <no private>]
    --[private]--> 0000018618BD74F0 [Object <no private>]
    --[attributes]--> 0000018604CEB100 [Map 186065f8e20]
    --[value]--> 0000018604CEB160 [Set 186065f8eb0]
    --[key]--> 000001860F07C3C0 [Object <no private>]
    --[unboxed_object]--> 00000186125DF240 [Object <no private>]
    --[audioBtn]--> 0000018604C9AA80 [Proxy <no private>]
    --[private]--> 000001860DB7E4C0 [HTMLDivElement <no private>]
    --[shape]--> 000001860F0C6088 [shape]
    --[base]--> 000001861443F718 [base_shape]
    --[global]--> 000001860F0C7240 [Window <no private>]
```

**Comment by Quicksaver** [comment]
Thanks, looking into it. Side-note, how did you get that detailed info? Some add-on or exterior app?

**Comment by the8472** [comment]
The analysis is done by saving the verbose CC&GC logs from about:memory and then digging through them with find_roots.py from https://github.com/amccreight/heapgraph

**Comment by the8472** [comment]
Also, instead of instrumenting hundreds of dom nodes, which is a horrible horrible thing to do you can take a look at `tabbrowser.xml` and see what it does http://mxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/browser.xml#688

It handles those audio things through DOM events and message manager messages, which could be instrumented at the window level / via message messagers.

**Comment by Quicksaver** [comment]
> It seems that tabview.xhtml is now kept alive after disabling the addon.

Should be fIxed in the latest commit.

> It handles those audio things through DOM events and message manager messages, which could be instrumented at the window level / via message messagers.

Only one Mutation Observer is being used per tab, the perf difference from adding or removing an attribute or two from its list should be negligible, especially considering how audio attribute changes pale in comparison to ``´busy``` or ```pending``` attribute changes for instance.

**Comment by the8472** [comment]
`tabview.xhtml` leak is gone, the dom/memory-file-data issue still remains.

**Comment by Quicksaver** [comment]
> the dom/memory-file-data issue still remains.

I still can't reproduce it, at least as far as usual suspects go (canvases, thumbs...) they all seem to be properly discarded whenever they're not needed anymore for me. Nothing lingering for longer than it should. I tried leaving an active YouTube on the other day for a few hours, didn't see any crazy build up of data like that. :(

**Comment by the8472** [comment]
Someone at mozilla was able to reproduce it, but apparently its hard to track down the cause even for them.

https://bugzilla.mozilla.org/show_bug.cgi?id=1272078

**Comment by Quicksaver** [comment]
Well I just tried again, and now I can reproduce it easily. I have no idea why, maybe I was doing something different without noticing before...

**Comment by daidoji** [comment]
I'd like to +1 this one also.  I love the addon, but noticed that extensively switching to sites I thought were js-heavy (although the redraw thing makes more sense) caused my browser to crash a lot, have "unresponsive script" errors, and become generally unuseable.  

Disabling and re-enabling the add-on seems to work and the only other extension I run is adblockplus.  I've also disabled thumbnails per your suggestion further above and that seems to work as well.  It def is a race condition as I can't reproduce it entirely, but FF does crash about 2-4x a day for me with this addon enabled.

Per @the8472 it does seem to happen frequently on youtube, but also gmail, slack, outlook365 and other single page apps with heavy js usage.  I also frequently get "unresponsive script" errors from GoogleTalk/Hangouts plugin and sometimes run Hangouts in separate browser windows (but attached to the same profile).

I'm on Linux running latest stable FF 48.0.2 with updated tab groups addon.  I hope this was helpful and except for these crashes it really is a nice plugin.  Thanks for all the work.  If you need anything else from me that might help troubleshoot this feel free to reach out to me.
