### ISSUE TITLE
Closing the last tab in a tab group opens a tab from another tab group

### ISSUE THREAD

**Issue by allo-** [Quicksaver/Tab-Groups#369]
With browser.tabs.closeWindowWithLastTab;false you can close all tabs in a window, without closing the window.
Tabgroups respected this in recent versions and opened a new empty tab in the current group, when closing the last one in the group.

Now it opens a tab from another group (seems like the last used before the current one?).
It does not close the old group, you can open the group view and click the "+" button on the empty group and get back to the group you used when closing the last tab in it.

expected behaviour:
- closing tabs should never switch the group (or there should at least be an option that the group is never switched when closing tabs)

actual behaviour:
- When the last tab of a group is closed, i.e. by middle clicking on it, a tab from another group is loaded and the other group activated.

**Comment by Quicksaver** [comment]
Two points:
- does it keep the group if you close the last tab in the group or if you close the "new tab" that opens when you close the last "actual tab" in the group?
- does this also happen if you disable all your other add-ons except for Tab Groups?

**Comment by allo-** [comment]
- fresh profile
- close on last tab = false
- open two group
- open one tab each (switched from second back to first then)
- close the tab in the first with a middle click on the tab

- second group is now open

**Comment by Arcesilas** [comment]
Same problem since yesterday. Not present before, or did not notice (unlikely, since I hate my browser choose for me).
I use groups like workspaces: closing the last tab of the group does not mean I want to do something else. It's like cleaning all your paintbrush does not mean you don't want to continue painting.

**Comment by allo-** [comment]
I think this only happens, when one tab from the other group is loaded. After a start where the tabs from other groups are inactive, it seems to stay in the same group after closing the last tab in the group.

**Comment by adamhill** [comment]
I have another bug similar to this one, that hits seemingly randomly. I am in my "Main" group, I will scroll to the right in the tab bar when many tabs are open and I will see tabs from another group.

The right hand side indicator says I am still in the Main group, but I see tabs from a single, other group. When I click on "Main" I get the dropdown and it shows me correctly in the other group.

1) I cannot repeat this behavior reliably.
2) When I scroll back to the left hand side the correct tabs (ones I had opened earlier in the day) are visible, but when I scroll back to the right the tabs from another group are visible again. In group indicator still says "Main".

Anything you would like me to try? Do you want me to make a separate issue?

**Comment by Quicksaver** [comment]
> Anything you would like me to try?

Does that also happen if you disable all your other add-ons except for Tab Groups?

> Do you want me to make a separate issue?

Yes, please, it seems fairly different from this that I'm not sure if it could be the same thing.

**Comment by Quicksaver** [comment]
I can't reproduce this at all. Does this still happen for anyone? What operating system, Firefox version and Tab Groups version are you using?

**Comment by allo-** [comment]
Currently it seems not to happen always, i am not sure under what circumstances it happens.
I am not experimenting too much, as i have quite a bit of tab groups i do not want to change too much currently. Last try to reproduce was the one at 9 Jul.

**Comment by Quicksaver** [comment]
I've tried those exact steps in a clean profile, with the latest release of Tab Groups as well as with my local copy. I've also tried a few variations and in other Firefox versions. I didn't see it once. Closing the last tab in a group always opens a new tab in the same group for me; only if I close that new tab, it will close the empty group (if I have that option enabled in Tab Group's preferences of course) and take me to groups view.

**Comment by allo-** [comment]
Still happens, but not fully sure what triggers it.

Currently it seems to be reproducable this way:
- close all tabs with middle click
- empty tab opens
- close empty tab with middle click
- overview opens
- create a new tab clicking the + in the empty group in the tab group overview
- now click on a website from the new tab page
- close the tab with middle click
- next group is opened, without change animation or simliar to notice what happened.

I think closing an empty tab which was opened after the last website tab is closed doesn't make sense anyway (and opening the overview is a good behaviour), but the behaviour afterwards seems to be exactly the bug and i think it happens under other conditions (currently no idea which ones) as well.

**Comment by Quicksaver** [comment]
Nope, those steps work fine for me as well, tried many times again. Were these in a clean profile?

> - close all tabs with middle click
- empty tab opens
- close empty tab with middle click
- overview opens
- create a new tab clicking the + in the empty group in the tab group overview

To clarify, at this point the group didn't close for you? Note that empty groups are closed automatically by default, unless you disable that option in the add-on's preferences or if you give it a name or change any of its default per-group settings. So at least in your example from before in the clean profile, this group should no longer exist. Please let me know if you did change its name or something similar, otherwise you should have no empty group at this point.

**Comment by Quicksaver** [comment]
BTW I still don't know your OS, Firefox version and Tab Groups version. ;)

**Comment by allo-** [comment]
Ah, sorry. Linux, Firefox 45esr and Tabgroups 2.0.1. Fresh test profile with just tabgroups installed.
preferences changed: 

- toolbarbutton is no quickchooser, but the button for the overview
- overview mode changed to free mode (movable groups)

Tab group did close some times and some times it was empty with just a "+" tile inside. I think i need to find a better minimal way to reproduce it. Possibly it got better on my main profile, because i use one of the grid-modes there, not the old style mode.

**Comment by Arcesilas** [comment]
I also still have this problem. A workaround I've set up is to configure Tab Mix Plus to avoid last tab to be closed.

What I do:
- open a new group
- open a new tab (with a page loaded)
- close the tab
=> the group is not deleted, but it is automatically switched to another one with at least one page in a tab.

I've been able to not reproduce it (yes, it sounds weird, I know): at one moment, closing the last tab did not switch to another group. It was just 2 or 3 minutes before I could have the "normal" behaviour (switching to another group). Cannot explain better my experience: I just don't understand what happened right now...

Configuration:
- Linux (Ubuntu 15.10)
- Firefox 47.0
- Tab Groups 2.0.1
- Tab Mix Plus 0.5.0.0
(N.B.: I consider not using Tab Mix Plus not worth considering)

**Comment by Quicksaver** [comment]
Oooh there it is! I can reproduce it in Linux. Let me see what I can do.

**Comment by allo-** [comment]
I am a bit curious: What was the issue and why is it linux specific?

**Comment by Quicksaver** [comment]
Backstory: Firefox can't have no tabs open. Period. If you close the last visible tab, it will always try to either i) focus another tab, or ii) open a new tab. By default, when you close the last visible tab (of the current group), it would try to load a tab from another group and thus switch to that group, which is what was happening.

Basically, there's a flag in the window object that's set when the last visible tab closes and it takes you to groups view; this flag is at the same time a placeholder blank tab that is opened (and that you never see), in order to not load another "random" tab like I explained above; there's no point in loading a tab that you don't plan to visit after all.

This flag is cleared (and the placeholder tab is removed, which is why you never see it normally) when it receives the signal that you left groups view to activate another group or open a new tab or whatever. For some reason, that signal never reached the appropriate handler in the window, I don't really know why, it probably has to do with how events travel across frames, although anything beyond that would be pure speculation on my part. So that flag was never cleared, and when you closed the last visible tab the second time, the add-on got confused because the placeholder flag was already set when it shouldn't have been. So things misbehaved...

I just had to switch the place at which it was listening for that event, so that it clears the placeholder flag appropriately. :)

**Comment by Quicksaver** [comment]
> it probably has to do with how events travel across frames

To clarify, it seems like it was Linux specific (it could also have been happening on Mac OSX, I didn't test it there to be honest) because it was working fine in Windows, it was receiving the event about leaving groups view just fine there.

**Comment by allo-** [comment]
Ah, thank you for the explanation :-).

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this behavior. Please give it a try and let me know how it works for you.

**Comment by allo-** [comment]
Installing it. Will i still get updates from AMO or do i need to remember to switch back to the official version later?

**Comment by Quicksaver** [comment]
It will (or should at least) update automatically once I upload the final version to AMO.
